from django.urls import path

from hostelapp import views, adminviews, studentviews

urlpatterns=[
    path('',views.homepage,name='homepage'),
    path('loginpage',views.loginpage,name="loginpage"),
    path('log_out',views.log_out,name="log_out"),
    path('regis',views.regis,name="regis"),
    path('stureg',views.stureg,name="stureg"),
    path('pareg',views.pareg,name="pareg"),
    path('wareg',views.wareg,name="wareg"),
    path('adminpage',views.adminpage,name="adminpage"),
    path('parentpage',views.parentpage,name="parentpage"),
    path('studentpage',views.studentpage,name="studentpage"),
    path('studentpage',views.studentpage,name="studentpage"),
    path('wardenpage',views.wardenpage,name="wardenpage"),

    path('addhostel',adminviews.addhostel,name="addhostel"),
    path('base',adminviews.base,name="base"),
    path('view_hostel',adminviews.view_hostel,name="view_hostel"),
    path('update_hostel/<int:id>/',adminviews.update_hostel,name="update_hostel"),
    path('deletehostel/<int:id>/',adminviews.deletehostel,name="deletehostel"),
    path('addfood',adminviews.addfood,name="addfood"),
    path('viewfood',adminviews.viewfood,name="viewfood"),
    path('updatefood/<int:id>/',adminviews.updatefood,name="updatefood"),
    path('deletefood/<int:id>/',adminviews.deletefood,name="deletefood"),
    path('notiadd',adminviews.notiadd,name="notiadd"),
    path('notiview',adminviews.notiview,name="notiview"),
    path('notiupdate/<int:id>/',adminviews.notiupdate,name="notiupdate"),
    path('deletenoti/<int:id>/',adminviews.deletenoti,name="deletenoti"),
    path('wardenreg',adminviews.wardenreg,name="wardenreg"),
    path('wardenview',adminviews.wardenview,name="wardenview"),
    path('wardenupdate/<int:id>/',adminviews.wardenupdate,name="wardenupdate"),
    path('wardendel/<int:id>/',adminviews.wardendel,name="wardendel"),
    path('viewreg',adminviews.viewreg,name="viewreg"),
    path('approve_student/<int:id>/',adminviews.approve_student,name="approve_student"),
    path('reject_student/<int:id>/',adminviews.reject_student,name="reject_student"),
    path('approve_parent/<int:id>/',adminviews.approve_parent,name="approve_parent"),
    path('reject_parent/<int:id>/',adminviews.reject_parent,name="reject_parent"),
    path('viewreview_admin',adminviews.viewreview_admin,name="viewreview_admin"),
    path('complaint_view',adminviews.complaint_view,name="complaint_view"),
    path('reply_complaint/<int:id>/',adminviews.reply_complaint,name="reply_complaint"),
    path('view_booking',adminviews.view_booking,name="view_booking"),
    path('confirm_booking/<int:id>/',adminviews.confirm_booking,name="confirm_booking"),
    path('reject_booking/<int:id>/',adminviews.reject_booking,name="reject_booking"),
    path('add_attendance',adminviews.add_attendance,name="add_attendance"),
    path('mark/<int:id>/',adminviews.mark,name="mark"),
    path('view_attendance',adminviews.view_attendance,name="view_attendance"),
    path('day_attendance/<date>/',adminviews.day_attendance,name="day_attendance"),

    path('base1',studentviews.base1,name="base1"),
    path('viewhostel',studentviews.viewhostel,name="viewhostel"),
    path('book_room',studentviews.book_room,name="book_room"),
    path('booking_status',studentviews.booking_status,name="booking_status"),
    path('add_review',studentviews.add_review,name="add_review"),
    path('viewreview',studentviews.viewreview,name="viewreview"),
    path('add_complaint',studentviews.add_complaint,name="add_complaint"),
    path('view_complaint',studentviews.view_complaint,name="view_complaint"),

]